# Docker componse for couchbase server and spring boot application
version: "3.1"
services:
  couchbase:
    build:
      context: .
      dockerfile: Dockerfile-couchbase-server
    container_name: couchbase
    ports:
      - "9091-9094:8091-8094"
      - "21210:11210"
    environment:
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      CLUSTER_NAME: default
      SERVICES: data,index,query,fts
      CLUSTER_RAMSIZE: 500
      BUCKET: travel-sample
      BUCKET_RAMSIZE: 300
      NODE_INIT_INDEX_PATH: /opt/couchbase/var/lib/couchbase/indexes
    volumes:
      - .docker/couchbase:/opt/couchbase/var

    networks:
      - couchbase-network
  java-springboot-quickstart:
    build:
      context: .
      dockerfile: Dockerfile-java-springboot-quickstart
    container_name: java-springboot-quickstart
    ports:
      - 9090:8080
    depends_on:
      - couchbase
    networks:
      - couchbase-network

networks:
  couchbase-network:
    driver: bridge


    # environment:
    #   - COUCHBASE_ADMINISTRATOR_USERNAME=admin
    #   - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    #   - COUCHBASE_BUCKET_NAME=sample
    #   - COUCHBASE_BUCKET_TYPE=couchbase
    #   - COUCHBASE_BUCKET_RAM_SIZE=100
    #   - COUCHBASE_BUCKET_REPLICA=1
    #   - COUCHBASE_SERVICES=data,index,query,fts
    #   - COUCHBASE_INDEX_STORAGE_SETTING=memopt
    #   - COUCHBASE_MEMORY_QUOTA=300
    #   - COUCHBASE_FTS_MEMORY_QUOTA=300
    #   - COUCHBASE_EVENTING_MEMORY_QUOTA=300
    #   - COUCHBASE_ANALYTICS_MEMORY_QUOTA=300
    #   - COUCHBASE_PORT=8091
    #   - COUCHBASE_QUERY_PORT=8093
    #   - COUCHBASE_INDEX_PORT=8094
    #   - COUCHBASE_FTS_PORT=8095
    #   - COUCHBASE_EVENTING_PORT=8096
    #   - COUCHBASE_ANALYTICS_PORT=8097
    #   - COUCHBASE_SERVICES=data,index,query,fts
    #   - COUCHBASE_INDEX_STORAGE_SETTING=memopt
    #   - COUCHBASE_MEMORY_QUOTA=300
    #   - COUCHBASE_FTS_MEMORY_QUOTA=300
    #   - COUCHBASE_EVENTING_MEMORY_QUOTA=300
    #   - COUCHBASE_ANALYTICS_MEMORY_QUOTA=300
    #   - COUCHBASE_PORT=8091
    #   - COUCHBASE_QUERY_PORT=8093
    #   - COUCHBASE_INDEX_PORT=8094
    #   - COUCHBASE_FTS_PORT=8095
    #   - COUCHBASE_EVENTING_PORT=8096
    #   - COUCHBASE_ANALYTICS_PORT=8097
    #   - COUCHBASE_SERVICES=data,index,query,fts
    #   - COUCHBASE_INDEX_STORAGE_SETTING=memopt
    #   - COUCHBASE_MEMORY_QUOTA=300
    #   - COUCHBASE_FTS_MEMORY_QUOTA=300
    #   - COUCHBASE_EVENTING_MEMORY_QUOTA=300
    #   - COUCHBASE_ANALYTICS_MEMORY_QUOTA=300