# read up on using workflow dispatch - it allows you to run actions manually
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

# read up on using helm to deploy operator and the cluster - it's easy mode
# https://docs.couchbase.com/operator/current/helm-setup-guide.html

# friendly charts can be found here
# https://github.com/couchbase-partners/helm-charts

# read up on KIND (Kubernetes in Docker)
# https://kind.sigs.k8s.io/docs/user/quick-start/

# this will spin up a KIND K8S cluster, install the operator, admission, and 1 x Couchbase Cluster node based on the values passsed in the operator-values.yaml file found in the deployment directory

name: "Create cluster using KinD"
on:
  workflow_dispatch

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: engineerd/setup-kind@v0.5.0
      - name: Install Helm
        uses: azure/setup-helm@v1
      - name: Install the operator
        run: |
          helm repo add couchbase https://couchbase-partners.github.io/helm-charts/
          helm repo update
          helm install default --values deployment/operator-values.yaml couchbase/couchbase-operator
      - name: validate the pods for couchbase
        run: |
          sleep 60
          echo 'Get IP Address of Cluster'
          echo '*************************'
          kubectl get pod default-couchbase-cluster-0000 --template={{.status.hostIP}}
          export $envIpAddress = $(kubectl get pod default-couchbase-cluster-0000 --template={{.status.hostIP}})
          echo 'IP Address of Cluster -> $envIpAddress'
          echo 'Get Port of Cluster'
          echo '*******************'
          kubectl get service default-couchbase-cluster-0000 -n default 

          kubectl port-forward --namespace default default-couchbase-cluster-0000 8091:8091 &
          kubectl port-forward --namespace default default-couchbase-cluster-0000 8092:8092 &
          kubectl port-forward --namespace default default-couchbase-cluster-0000 8093:8093 &
          kubectl port-forward --namespace default default-couchbase-cluster-0000 9140:9140 &
          kubectl port-forward --namespace default default-couchbase-cluster-0000 11210:11210 &
        env:
          envIpAdress: 127.0.0.1
          envPort: 809
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml